会場をインプレスに更新した
masudamegumi/ichiyasaGitSample pull request #1
Opened 2024-06-06 05:16 UTC by masudamegumi

変更

2024-06-06 05:36 UTC, sunaga0 commented
コメントが短いです。

2024-06-06 05:37 UTC, atsuki-g-2 commented
ぼくのみてください

2024-06-12 02:36 UTC, atsuki-g-2 requested changes
あうあうあう

2024-06-12 02:36 UTC, atsuki-g-2 commented on index.html
>                          <h3>スピーカー</h3>
株式会社FANZAに変えてください

2024-06-12 03:10 UTC, atsuki-g-2 commented
今回はちゃんと作りました

2024-06-12 03:16 UTC, masudamegumi reviewed
レビューお願いします

2024-06-13 04:35 UTC, atsuki-g-2 approved these changes
いいですよ

2024-06-13 04:41 UTC, sunaga0 approved these changes
変更大丈夫です

2024-06-13 04:57 UTC, merged